import type { Metadata } from "next";
import { Noto_Sans as NotoSans } from "next/font/google";
import "./globals.css";

const notoSans = NotoSans({
  variable: "--noto-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});


export const metadata: Metadata = {
  title: "Zipdocs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} noto-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
